version: '3'

volumes:
  postgres-rails:

services:
  rails-blueprint:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: mamazary/rails-blueprint
    env_file:
      - ./docker/docker-compose-rails.env
    ports:
      - 3000:3000

  postgres-server:
    image: postgres:11
    restart: always
    env_file:
      - ./docker/docker-compose-postgres.env
    volumes:
      - postgres-rails:/var/lib/postgresql/data
